[build-system]
requires = ["setuptools>=61.0", "wheel", "pybind11>=2.10"]
build-backend = "setuptools.build_meta"

[project]
name = "pycpu"
version = "0.1.0"
description = "High-level CPU simulation and RISC assembler powered by CPU.cpp"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pylogic>=0.1.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: C++",
    "Topic :: System :: Hardware"
]
